[build]
  command = "CI=false npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  NODE_VERSION = "18"

# Redirects for API endpoints
[[redirects]]
  from = "/api/llm"
  to = "/.netlify/functions/openai-proxy"
  status = 200
  force = true

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
